import os
import re
from abc import ABC, abstractmethod
from collections.abc import AsyncGenerator

import google.generativeai as genai
import openai

from app.core.config import settings
from app.core.exceptions import AIError
from app.core.logging import logger


class BaseLLMProvider(ABC):
    """
    Abstract interface for swappable LLM model providers.
    Supports standard and streaming text synthesis.
    """

    @abstractmethod
    async def generate_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> str:
        """
        Generates a non-streaming text response.
        """
        pass

    @abstractmethod
    async def stream_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> AsyncGenerator[str, None]:
        """
        Yields text chunks as they are generated by the model.
        """
        # Yield is inside concrete implementations
        pass


class OpenAILLMProvider(BaseLLMProvider):
    """OpenAI implementation using the official async client."""

    def __init__(self) -> None:
        self.model = getattr(settings, "OPENAI_MODEL", "gpt-4o-mini")

    def _get_client(self) -> openai.AsyncOpenAI:
        api_key = settings.OPENAI_API_KEY or os.environ.get("OPENAI_API_KEY", "")
        if not api_key:
            raise AIError(message="OPENAI_API_KEY is not configured in .env file.")
        return openai.AsyncOpenAI(api_key=api_key)

    async def generate_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> str:
        client = self._get_client()

        formatted_messages = []
        if system_prompt:
            formatted_messages.append({"role": "system", "content": system_prompt})
        formatted_messages.extend(messages)

        try:
            response = await client.chat.completions.create(
                model=self.model,
                messages=formatted_messages,
                temperature=0.2,  # Low temperature is critical for accurate RAG synthesis
            )
            return response.choices[0].message.content or ""
        except Exception as e:
            logger.error(f"OpenAI completion failed: {e}")
            raise AIError(message=f"OpenAI error: {str(e)}", details={"error": str(e)}) from e

    async def stream_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> AsyncGenerator[str, None]:
        client = self._get_client()

        formatted_messages = []
        if system_prompt:
            formatted_messages.append({"role": "system", "content": system_prompt})
        formatted_messages.extend(messages)

        try:
            response = await client.chat.completions.create(
                model=self.model,
                messages=formatted_messages,
                temperature=0.2,
                stream=True,
            )
            async for chunk in response:
                if chunk.choices and chunk.choices[0].delta.content:
                    yield chunk.choices[0].delta.content
        except Exception as e:
            logger.error(f"OpenAI streaming completion failed: {e}")
            raise AIError(message=f"OpenAI error: {str(e)}", details={"error": str(e)}) from e


class GeminiLLMProvider(BaseLLMProvider):
    """Gemini implementation using the async google-generativeai SDK with automatic model fallback."""

    def __init__(self) -> None:
        self._cached_model = "gemini-2.0-flash"
        api_key = settings.GEMINI_API_KEY or os.environ.get("GEMINI_API_KEY", "")
        if api_key:
            genai.configure(api_key=api_key)

    def _convert_messages(self, messages: list[dict]) -> list[dict]:
        """Maps standard message structures to Gemini contents schema (user -> model)."""
        gemini_contents = []
        for msg in messages:
            role = msg["role"]
            if role == "assistant":
                role = "model"
            if role == "system":
                continue
            gemini_contents.append(
                {
                    "role": role,
                    "parts": [msg["content"]],
                }
            )
        return gemini_contents

    async def generate_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> str:
        api_key = settings.GEMINI_API_KEY or os.environ.get("GEMINI_API_KEY", "")
        if not api_key:
            raise AIError(message="GEMINI_API_KEY is not configured.")

        genai.configure(api_key=api_key)
        contents = self._convert_messages(messages)
        candidate_models = ["gemini-2.0-flash", "gemini-1.5-flash", "gemini-1.5-pro", "gemini-pro"]

        last_error = None
        for model_name in candidate_models:
            try:
                model = genai.GenerativeModel(
                    model_name=model_name,
                    system_instruction=system_prompt,
                )
                response = await model.generate_content_async(
                    contents=contents,
                    generation_config=genai.types.GenerationConfig(temperature=0.0),
                )
                text = response.text or ""
                text = re.sub(r"<think>[\s\S]*?</think>", "", text).strip()
                logger.info(f"Gemini responded successfully using model: {model_name}")
                return text
            except Exception as e:
                logger.warning(f"Gemini model '{model_name}' failed: {e}. Trying next candidate...")
                last_error = e

        raise AIError(message=f"Gemini error: {str(last_error)}", details={"error": str(last_error)})

    async def stream_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> AsyncGenerator[str, None]:
        full_text = await self.generate_response(messages, system_prompt)
        yield full_text


class GroqLLMProvider(BaseLLMProvider):
    """Groq implementation with robust model discovery and multi-model execution."""

    def __init__(self) -> None:
        self._cached_model: str | None = None

    def _get_client(self) -> openai.AsyncOpenAI:
        api_key = settings.GROQ_API_KEY or os.environ.get("GROQ_API_KEY", "")
        if not api_key:
            raise AIError(message="GROQ_API_KEY is not configured in .env file.")
        return openai.AsyncOpenAI(
            base_url="https://api.groq.com/openai/v1",
            api_key=api_key,
        )

    async def _get_usable_models(self, client: openai.AsyncOpenAI) -> list[str]:
        if self._cached_model:
            return [self._cached_model]

        user_specified = os.environ.get("GROQ_MODEL") or getattr(settings, "GROQ_MODEL", None)
        valid_models = []

        try:
            m_list = await client.models.list()
            all_ids = [m.id for m in m_list.data]
            logger.info(f"Groq API returned available models: {all_ids}")
            
            # Filter out non-chat models (audio, guards, terms-requiring)
            chat_models = [
                m_id for m_id in all_ids 
                if not m_id.startswith("canopylabs") 
                and not m_id.startswith("whisper")
                and "guard" not in m_id
            ]
            if chat_models:
                valid_models = chat_models
        except Exception as e:
            logger.warning(f"Could not list Groq models: {e}")

        # Preference priority matching active models on this key
        preferred_order = [
            "groq/compound",
            "groq/compound-mini",
            "qwen/qwen3.6-27b",
            "openai/gpt-oss-20b",
            "openai/gpt-oss-120b",
            "llama-3.3-70b-versatile",
            "llama-3.1-70b-versatile",
            "llama-3.1-8b-instant",
            "allam-2-7b",
        ]
        ordered_candidates = []
        if user_specified and user_specified in valid_models:
            ordered_candidates.append(user_specified)

        for pref in preferred_order:
            if pref in valid_models and pref not in ordered_candidates:
                ordered_candidates.append(pref)

        for remaining in valid_models:
            if remaining not in ordered_candidates:
                ordered_candidates.append(remaining)

        if not ordered_candidates:
            ordered_candidates = ["groq/compound", "groq/compound-mini", "qwen/qwen3.6-27b", "openai/gpt-oss-20b"]

        return ordered_candidates

    async def generate_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> str:
        client = self._get_client()
        candidates = await self._get_usable_models(client)

        formatted_messages = []
        if system_prompt:
            formatted_messages.append({"role": "system", "content": system_prompt})
        formatted_messages.extend(messages)

        last_error = None
        for model_name in candidates:
            try:
                response = await client.chat.completions.create(
                    model=model_name,
                    messages=formatted_messages,
                    temperature=0.0,
                )
                raw_text = response.choices[0].message.content or ""
                # Strip internal reasoning/thinking tags (e.g. <think>...</think>)
                cleaned_text = re.sub(r"<think>[\s\S]*?</think>", "", raw_text).strip()
                self._cached_model = model_name
                logger.info(f"Groq responded successfully using model: {model_name}")
                return cleaned_text
            except Exception as e:
                logger.warning(f"Groq model '{model_name}' failed: {e}. Trying next candidate...")
                last_error = e

        raise AIError(message=f"Groq error: {str(last_error)}", details={"error": str(last_error)})

    async def stream_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> AsyncGenerator[str, None]:
        full_text = await self.generate_response(messages, system_prompt)
        yield full_text


def get_llm_provider() -> BaseLLMProvider:
    """
    Factory function returning the configured LLM provider.
    Supports Gemini (Google AI Studio), Groq, and OpenAI.
    """
    provider = settings.DEFAULT_LLM_PROVIDER.lower()
    has_gemini = bool(settings.GEMINI_API_KEY or os.environ.get("GEMINI_API_KEY"))
    has_groq = bool(settings.GROQ_API_KEY or os.environ.get("GROQ_API_KEY"))
    has_openai = bool(settings.OPENAI_API_KEY or os.environ.get("OPENAI_API_KEY"))

    if provider in ["gemini", "google"]:
        return GeminiLLMProvider()
    elif provider == "groq":
        return GroqLLMProvider()
    elif provider == "openai":
        return OpenAILLMProvider()
    elif has_gemini:
        return GeminiLLMProvider()
    elif has_groq:
        return GroqLLMProvider()
    else:
        return OpenAILLMProvider()


# Shared system-wide LLM generator client
llm_provider = get_llm_provider()
